apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: xray-exporter
build:
  artifacts:
    - image: anatolykopyl/xray-exporter
      docker:
        buildArgs:
          ARCH: amd64
deploy:
  kustomize:
    paths:
      - k8s
